---
id: 201711-model-driven-design
base_name: 201711-model-driven-design
tags:
- rabbit
- DDD
- bounded context
- microservices
presentation_date: 2017-11-28
version: 2017.11.04.1
licenses:
- MIT
slideshare_id:
speaker_deck_id: 
ustream_id: 
vimeo_id: 
youtube_id: 
author:
  markup_language: :rd
  name: Giovanni Sakti
  email: giosakti@gmail.com
  rubygems_user: giosakti
  slideshare_user:
  speaker_deck_user: giosakti 
